sudo: required

language: generic

services:
- docker

before_install:
- docker pull scottfleischman/agda:2.5.3

script:
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.3 /bin/sh -c 'cd /opt/agda-build; agda Agda-01-Syntax.agda'
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.3 /bin/sh -c 'cd /opt/agda-build; agda Agda-02-Dependent.agda'
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.3 /bin/sh -c 'cd /opt/agda-build; agda Agda-03-Modules.agda'
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.3 /bin/sh -c 'cd /opt/agda-build; agda Agda-04-Coinduction.agda'
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.3 /bin/sh -c 'cd /opt/agda-build; agda Agda-05-InductionRecursion.agda'
